### ISSUE TITLE
Failed to parse manifest data: No value for releaseId

### ISSUE THREAD

**Issue by Giasinit** [umbertoghio/self-hosted-expo-updates-server#2]
Buonasera, sono sempre io :)
volevo dirti che sono riuscito a fare tutto tranne aggiornare l'app.
Ho installato anche il tuo pacchetto per gli aggiornamenti abilitando i log e usando Logcat di Android studio e ho riscontrato sta volta questo errore:
```
2023-03-18 23:17:01.497 12684-12738/it.takeby E/UpdatesModule: Failed to parse manifest data: No value for releaseId
    org.json.JSONException: No value for releaseId
        at org.json.JSONObject.get(JSONObject.java:398)
        at org.json.JSONObject.getString(JSONObject.java:559)
        at expo.modules.manifests.core.LegacyManifest.getReleaseId(LegacyManifest.kt:37)
        at expo.modules.updates.manifest.LegacyUpdateManifest$Companion.fromLegacyManifest(LegacyUpdateManifest.kt:112)
        at expo.modules.updates.manifest.ManifestFactory.getManifest(ManifestFactory.kt:21)
        at expo.modules.updates.loader.FileDownloader$Companion.checkCodeSigningAndCreateManifest(FileDownloader.kt:462)
        at expo.modules.updates.loader.FileDownloader$Companion.access$checkCodeSigningAndCreateManifest(FileDownloader.kt:398)
        at expo.modules.updates.loader.FileDownloader.parseManifest(FileDownloader.kt:274)
        at expo.modules.updates.loader.FileDownloader.parseManifestResponse$expo_updates_release(FileDownloader.kt:119)
        at expo.modules.updates.loader.FileDownloader$downloadManifest$1.onResponse(FileDownloader.kt:319)
        at expo.modules.updates.loader.FileDownloader$downloadData$1.onResponse(FileDownloader.kt:393)
        at okhttp3.internal.connection.RealCall$AsyncCall.run(RealCall.kt:519)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1137)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:637)
        at java.lang.Thread.run(Thread.java:1012)
2023-03-18 23:17:01.541 12684-12721/it.takeby I/ReactNativeJS: doUpdateIfAvailable: ERROR: Failed to parse manifest data: No value for releaseId
```
P.S. ho fatto tutto come si deve, ho anche fatto l'upload di una modifica e tutto, però il `Release Channel` l'ho chiamato `stabiletake`, ovvero un nome a caso con cui ho corrisposto il link di upload anche sul app.json e sul relativo androidmanifest.xml

**Comment by umbertoghio** [comment]
Quale versione di Expo usi?
Provo a fare delle verifiche domani sera e ti aggiorno
Il 18 mar 2023, 23:26 +0100, Giasin ***@***.***>, ha scritto:

**Comment by Giasinit** [comment]
uso la versione ~47.0.12

**Comment by Giasinit** [comment]
Ma domani sera intendi oggi?

**Comment by Giasinit** [comment]
Buongiorno, a quanto pare dava il releaseId perchè non esisteva un aggiornamento precedente con lo stesso Release Channel, quindi risolto.
