### ISSUE TITLE
Web login

### ISSUE THREAD

**Issue by onebeat** [umbertoghio/self-hosted-expo-updates-server#30]
Hello, i have setup docker production version and  i cant login via admin/mypassword set in compose.yml file.

This is my debug code

`Attaching to self_hosted_expo_updates_server_api, self_hosted_expo_updates_server_db, self_hosted_expo_updates_server_web
self_hosted_expo_updates_server_db exited with code 0
self_hosted_expo_updates_server_web  | 2024/12/01 00:31:12 [notice] 30#30: using the "epoll" event method
self_hosted_expo_updates_server_web  | 2024/12/01 00:31:12 [notice] 30#30: nginx/1.27.0
self_hosted_expo_updates_server_web  | 2024/12/01 00:31:12 [notice] 30#30: built by gcc 13.2.1 20231014 (Alpine 13.2.1_git20231014) 
self_hosted_expo_updates_server_web  | 2024/12/01 00:31:12 [notice] 30#30: OS: Linux 5.14.0-503.15.1.el9_5.x86_64
self_hosted_expo_updates_server_web  | 2024/12/01 00:31:12 [notice] 30#30: getrlimit(RLIMIT_NOFILE): 1073741816:1073741816
self_hosted_expo_updates_server_web  | 2024/12/01 00:31:12 [notice] 30#30: start worker processes
self_hosted_expo_updates_server_web  | 2024/12/01 00:31:12 [notice] 30#30: start worker process 31
self_hosted_expo_updates_server_web  | 2024/12/01 00:31:12 [notice] 30#30: start worker process 32
self_hosted_expo_updates_server_web  | 2024/12/01 00:31:12 [notice] 30#30: start worker process 33
self_hosted_expo_updates_server_web  | 2024/12/01 00:31:12 [notice] 30#30: start worker process 34
self_hosted_expo_updates_server_api  | {"level":30,"time":1733013072185,"pid":1,"hostname":"b5d8222c396c","msg":"Feathers application started on http://localhost:3000"}
self_hosted_expo_updates_server_api  | {"level":30,"time":1733013072186,"pid":1,"hostname":"b5d8222c396c","msg":"Env: production DB: mongodb://expo:admin@10.11.11.43:27017/expo"}
self_hosted_expo_updates_server_api  | {"level":50,"time":1733013073193,"pid":1,"hostname":"b5d8222c396c","msg":"TypeError: Cannot read properties of undefined (reading 'find')\n    at Object._find (/home/node/server/node_modules/feathers-mongodb/lib/index.js:123:26)\n    at callMethod (/home/node/server/node_modules/@feathersjs/adapter-commons/lib/service.js:13:22)\n    at Object.find (/home/node/server/node_modules/@feathersjs/adapter-commons/lib/service.js:63:16)\n    at /home/node/server/node_modules/@feathersjs/feathers/lib/hooks/index.js:57:33\n    at new Promise (<anonymous>)\n    at /home/node/server/node_modules/@feathersjs/feathers/lib/hooks/index.js:54:27\n    at async createAdminIfMissing (/home/node/server/src/index.js:18:19)"}
self_hosted_expo_updates_server_api  | {"level":50,"time":1733013073194,"pid":1,"hostname":"b5d8222c396c","msg":"API - Unhandled Rejection at: Promise "}
self_hosted_expo_updates_server_api  | {"level":50,"time":1733013076378,"pid":1,"hostname":"b5d8222c396c","msg":"TypeError: Cannot read properties of undefined (reading 'find')\n    at Object._find (/home/node/server/node_modules/feathers-mongodb/lib/index.js:123:26)\n    at callMethod (/home/node/server/node_modules/@feathersjs/adapter-commons/lib/service.js:13:22)\n    at Object.find (/home/node/server/node_modules/@feathersjs/adapter-commons/lib/service.js:63:16)\n    at /home/node/server/node_modules/@feathersjs/feathers/lib/hooks/index.js:57:33\n    at new Promise (<anonymous>)\n    at /home/node/server/node_modules/@feathersjs/feathers/lib/hooks/index.js:54:27\n    at async Object.find (/home/node/server/src/services/status.js:17:22)"}
self_hosted_expo_updates_server_api  | {"level":50,"time":1733013076378,"pid":1,"hostname":"b5d8222c396c","msg":"API - public/status"}
self_hosted_expo_updates_server_api  | {"level":50,"time":1733013081543,"pid":1,"hostname":"b5d8222c396c","msg":"TypeError: Cannot read properties of undefined (reading 'find')\n    at Object._find (/home/node/server/node_modules/feathers-mongodb/lib/index.js:123:26)\n    at callMethod (/home/node/server/node_modules/@feathersjs/adapter-commons/lib/service.js:13:22)\n    at Object.find (/home/node/server/node_modules/@feathersjs/adapter-commons/lib/service.js:63:16)\n    at /home/node/server/node_modules/@feathersjs/feathers/lib/hooks/index.js:57:33\n    at new Promise (<anonymous>)\n    at /home/node/server/node_modules/@feathersjs/feathers/lib/hooks/index.js:54:27\n    at async Object.find (/home/node/server/src/services/status.js:17:22)"}
self_hosted_expo_updates_server_api  | {"level":50,"time":1733013081543,"pid":1,"hostname":"b5d8222c396c","msg":"API - public/status"}`

**Comment by umbertoghio** [comment]
The credentials in the compose file must match the init.js startup script of mongodb https://github.com/umbertoghio/self-hosted-expo-updates-server/blob/master/Docker/production/mongoinit/init.js

there's an admin password (line 2) and a user password (line 8) used for node to connect.
Please check this first and delete the mongodb self_hosted_mongo_data volume, as the init.js only works on the initial startup

**Comment by mgscreativa** [comment]
Hi @umbertoghio I have this very same issue, but without changing anything in the production docker-compoe file, can you take a look https://github.com/umbertoghio/self-hosted-expo-updates-server/issues/41

**Comment by umbertoghio** [comment]
see answer in #41
